services:
  clone-server:
    user: ${DOCKER_UID}:${DOCKER_GID}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID:-1000}
        - DOCKER_GID=${DOCKER_GID:-1000}
        - DOCKER_USER=${DOCKER_USER:-user}
    image: clone-unitree:ubuntu20.04
    container_name: clone_unitree_server
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/${DOCKER_USER}/CLONE:rw
      - ./:/home/${DOCKER_USER}/deploy:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=0
    devices:
      - /dev/bus/usb:/dev/bus/usb
    command: /bin/bash